### ISSUE TITLE
Invalid (empty) SARIF file generated

### ISSUE THREAD

**Issue by nelenkov** [returntocorp/sgrep-action#378]
The scan action generates an invalid SARIF file, causing the upload action to fail.

Maybe this is caused by this recent change: https://github.com/returntocorp/semgrep-action/commit/9e14dce842a906eec042c6c6383735cddfe20f96

It appears that Github is doing some validation on the SARIF file.

Output is below:

```
 using semgrep rules from https://semgrep.dev/c/p/phpcs-security-audit
| using path ignore rules from .semgrepignore
| not on head ref 09770910...; checking that out now...
| reporting findings introduced by these commits:
|   * 0977091 ....
| looking at No changed paths
| found No files in the paths to be scanned
=== looking for current issues in No files
| No current issues found
| No ignored issues found
| returning to original head revision efe2d174...
=== not looking at pre-existing issues since there are no current issues
=== re-running scan to generate a SARIF report
=== exiting with success status
1s
Run github/codeql-action/upload-sarif@v1
Uploading results
Error details: instance requires property "version"
Error details: instance requires property "runs"
Error: Unable to upload "semgrep.sarif" as it is not valid SARIF:
- instance requires property "version"
- instance requires property "runs"
Error: Unable to upload "semgrep.sarif" as it is not valid SARIF:
- instance requires property "version"
- instance requires property "runs"
    at validateSarifFileSchema (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-lib.js:196:15)
    at uploadFiles (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-lib.js:256:9)
    at Object.uploadFromActions (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-lib.js:132:18)
    at async run (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-sarif-action.js:49:29)
    at async runWrapper (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-sarif-action.js:61:9)
```

**Comment by ultras5631** [comment]
same issue there. any fixes?

**Comment by andyjones** [comment]
I'm hitting this as well when the PR being scanned hasn't changed any files that semgrep would scan (eg. readme or test files). #421 looks like the same issue as it says "found No files in the paths to be scanned" so it generates a serif file that only contains `{}`. 

Github validate the serif file against https://github.com/github/codeql-action/blob/main/src/sarif_v2.1.0_schema.json

**Comment by brendongo** [comment]
I think this is closed by https://github.com/returntocorp/semgrep-action/pull/457
