### ISSUE TITLE
GitPython submodule error

### ISSUE THREAD

**Issue by Sjord** [returntocorp/sgrep-action#381]
I am running into [an obscure error with git submodules](https://github.com/gitpython-developers/GitPython/issues/890), where it seems GitPython doesn't support the repo layout. It seems GitPython does not handle all submodule cases well, and there are no plans to fix it.

My repository is really an edge-case, in that it may be considered invalid. I can imagine that such edge cases are not going to be supported. However, git handles it fine while gitpython doesn't.

There are two problems here:
1. gitpython isn't exactly git, so it will handle edge cases differently.
2. gitpython "is deeply flawed and broken beyond repair" and "GitPython's submodules should be avoided as it's not a complete implementation anymore".

I think problem 1 is acceptable, but problem 2 is cause for concern, and may be reason to reconsider using GitPython. At the same time, I am not aware of a better git library for Python.

## Reproduction

Clone [this repository](https://github.com/Sjord/brokenrepo) which has a .gitmodules file that specifies a submodule, but the path it points to is a file:

.gitmodules contains:
```
[submodule "foo"]
path = foo
url = ../foo
```

And `foo` is a normal, empty file.

According to `git submodule`, there are no submodules. Requesting the submodules from gitpython raises an error:

```
$ python -c 'import git; git.Repo(".").submodules'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/sjoerdlangkemper/dev/test/semact/venv/lib/python3.9/site-packages/git/repo/base.py", line 368, in submodules
    return Submodule.list_items(self)
  File "/Users/sjoerdlangkemper/dev/test/semact/venv/lib/python3.9/site-packages/git/util.py", line 1103, in list_items
    out_list.extend(cls.iter_items(repo, *args, **kwargs))
  File "/Users/sjoerdlangkemper/dev/test/semact/venv/lib/python3.9/site-packages/git/objects/submodule/base.py", line 1266, in iter_items
    sm._name = n
AttributeError: 'Blob' object has no attribute '_name'
```

And similarly, semgrep-action gives an error:

```
$ docker run -v $(pwd):/src --workdir /src returntocorp/semgrep-agent:v1 semgrep-agent --config p/ci
| versions          - semgrep 0.65.0 on Python 3.9.7
| scan type         - full scan (set --baseline-ref to scan changed files only)
| environment       - running in environment git, triggering event is 'unknown'
| manage            - not logged in
=== setting up agent configuration
| using semgrep rules from https://semgrep.dev/c/p/ci
| using default path ignore rules of common test and dependency directories
An unexpected error occurred
ERROR:root:'Blob' object has no attribute '_name'
Traceback (most recent call last):
  File "/app/src/semgrep_agent/main.py", line 181, in main
    protected_main(**locals())
  File "/app/src/semgrep_agent/main.py", line 322, in protected_main
    results = semgrep.scan(
  File "/app/src/semgrep_agent/semgrep.py", line 401, in scan
    findings = get_findings(
  File "/app/src/semgrep_agent/semgrep.py", line 126, in get_findings
    targets = TargetFileManager(
  File "<attrs generated init semgrep_agent.targets.TargetFileManager>", line 7, in __init__
    self._paths = __attr_factory__paths(self)
  File "/app/src/semgrep_agent/targets.py", line 177, in _get_path_lists
    submodules = repo.submodules  # type: ignore
  File "/usr/local/lib/python3.9/site-packages/git/repo/base.py", line 364, in submodules
    return Submodule.list_items(self)
  File "/usr/local/lib/python3.9/site-packages/git/util.py", line 1028, in list_items
    out_list.extend(cls.iter_items(repo, *args, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/git/objects/submodule/base.py", line 1214, in iter_items
    sm._name = n
AttributeError: 'Blob' object has no attribute '_name'
```

**Comment by brendongo** [comment]
We have switched over to using subprocess to run git instead of git python. I'm assuming that would close this issue but let us know otherwise
