### ISSUE TITLE
Re-running scan to generate SARIF report times out

### ISSUE THREAD

**Issue by sim642** [returntocorp/sgrep-action#429]
This recently started happening to all of our semgrep workflows, e.g. https://github.com/goblint/analyzer/runs/4236663683?check_suite_focus=true#step:4:44.
As the log shows, semgrep first runs fine and finds no issues. Then it starts re-running scan to generate SARIF report and that for some reason does nothing but waste 30min, time out and thus fail without having generated it.

**Comment by brendongo** [comment]
Hi @sim642 are you able to run with setting the SEMGREP_AGENT_DEBUG env flag to 1

**Comment by sim642** [comment]
Sure! The workflow run with debugging enabled was here: https://github.com/goblint/analyzer/runs/4272519434?check_suite_focus=true#step:4:1. Since it's truncated and I'm not sure if the full thing is accessible for download or not, I'm attaching the full log here: [semgrep-30min.log](https://github.com/returntocorp/semgrep-action/files/7574251/semgrep-30min.log). It ends with the following:
```
2021-11-20T08:35:26.5809042Z === [DEBUG] [1.599  Info       Main.Run_semgrep     ] Analyzing docs/artifact-descriptions/sas21.md
2021-11-20T08:35:26.5809846Z === [DEBUG] [1.599  Info       Main.Run_rules       ] looking for (Analyze_rule.And
2021-11-20T08:35:26.5810396Z === [DEBUG]    [(Analyze_rule.Or
2021-11-20T08:35:26.5810977Z === [DEBUG]        [(Analyze_rule.Idents ["clear"]); (Analyze_rule.Idents ["reset"]);
2021-11-20T08:35:26.5812070Z === [DEBUG]          (Analyze_rule.Idents ["add"]); (Analyze_rule.Idents ["remove"]);
2021-11-20T08:35:26.5812757Z === [DEBUG]          (Analyze_rule.Idents ["replace"])]);
2021-11-20T08:35:26.5813293Z === [DEBUG]      (Analyze_rule.Or
2021-11-20T08:35:26.5813921Z === [DEBUG]         [(Analyze_rule.Idents ["iter"]); (Analyze_rule.Idents ["fold"])])
2021-11-20T08:35:26.5814889Z === [DEBUG]      ]) in docs/artifact-descriptions/sas21.md
2021-11-20T08:35:26.5816347Z === [DEBUG] [1.599  Info       Main.Match_rules     ] checking docs/artifact-descriptions/sas21.md with 1 rules
2021-11-20T08:35:26.5817375Z === [DEBUG] [1.620  Info       Main.Naming_AST      ] Naming_AST.resolve program
2021-11-20T08:35:26.5819492Z === [DEBUG] [1.599  Info       Main.Parse_with_caching] parsing docs/artifact-descriptions/sas21.md
2021-11-20T08:35:26.5821214Z === [DEBUG] [1.599  Info       Main.Parse_target    ] trying to parse with Pfff parser docs/artifact-descriptions/sas21.md
2021-11-20T08:35:26.5822145Z Exception in thread STDOUT/ERR thread for pid 71:
2021-11-20T08:35:26.5834015Z Traceback (most recent call last):
2021-11-20T08:35:26.5835126Z   File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
2021-11-20T08:35:26.5835763Z     self.run()
2021-11-20T08:35:26.5836406Z   File "/usr/local/lib/python3.9/threading.py", line 910, in run
2021-11-20T08:35:26.5837067Z     self._target(*self._args, **self._kwargs)
2021-11-20T08:35:26.5838308Z   File "/usr/local/lib/python3.9/site-packages/sh.py", line 1683, in wrap
2021-11-20T08:35:26.5838925Z     fn(*rgs, **kwargs)
2021-11-20T08:35:26.5839979Z   File "/usr/local/lib/python3.9/site-packages/sh.py", line 2688, in output_thread
2021-11-20T08:35:26.5840608Z     done = f.read()
2021-11-20T08:35:26.5841423Z   File "/usr/local/lib/python3.9/site-packages/sh.py", line 3177, in read
2021-11-20T08:35:26.5842079Z     self.write_chunk(chunk)
2021-11-20T08:35:26.5843258Z   File "/usr/local/lib/python3.9/site-packages/sh.py", line 3154, in write_chunk
2021-11-20T08:35:26.5844142Z     self.should_quit = self.process_chunk(chunk)
2021-11-20T08:35:26.5845073Z   File "/usr/local/lib/python3.9/site-packages/sh.py", line 3063, in process
2021-11-20T08:35:26.5845711Z     return handler(chunk)
2021-11-20T08:35:26.5846530Z   File "/usr/local/lib/python3.9/site-packages/sh.py", line 1766, in fn
2021-11-20T08:35:26.5847133Z     return handler(chunk, *a)
2021-11-20T08:35:26.5847717Z   File "/app/src/semgrep_agent/utils.py", line 47, in debug_echo
2021-11-20T08:35:26.5848404Z     text = "\n".join(prefix + line for line in text.splitlines())
2021-11-20T08:35:26.5849114Z   File "/app/src/semgrep_agent/utils.py", line 47, in <genexpr>
2021-11-20T08:35:26.5849954Z     text = "\n".join(prefix + line for line in text.splitlines())
2021-11-20T08:35:26.5850809Z TypeError: can only concatenate str (not "bytes") to str
2021-11-20T09:05:19.5059620Z Semgrep took longer than 1800 seconds to run or a git command took longer than 500 seconds; canceling this run
```
Looks like the `TypeError` happens immediately, but it doesn't fail the workflow, but just stays stuck for 30min after it.

**Comment by brendongo** [comment]
Forgot to follow up on this but https://github.com/returntocorp/semgrep-action/pull/437 should have solved the infinite loop above. Let us know if you see this again!
