### ISSUE TITLE
0.98.0 fails with git error on GHA

### ISSUE THREAD

**Issue by lwsanty** [returntocorp/sgrep-action#594]
We have a semgrep GHA
```yaml
  semgrep:
    name: Semgrep
    runs-on: ubuntu-20.04
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v1
      - name: Semgrep
        id: semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/r2c
```
And today it started failing with
```python
=== Running: SEMGREP_RULES="p/r2c" semgrep ci
Running `semgrep ci` without API token but with configs ('p/r2c',)
Scan environment:
  versions    - semgrep 0.[9](https://github.com/xxx/xxx-webapp/runs/6915050329?check_suite_focus=true#step:4:10)8.0 on python 3.[10](https://github.com/xxx/xxx-webapp/runs/6915050329?check_suite_focus=true#step:4:11).5
  environment - running in environment github-actions, triggering event is pull_request
Command '['git', 'fetch', 'origin', '--depth=1', '--force', '--update-head-ok', 'fix-semgrep:fix-semgrep']' returned non-zero exit status [12](https://github.com/xxx/xxx-webapp/runs/6915050329?check_suite_focus=true#step:4:13)8.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/semgrep/commands/wrapper.py", line 35, in wrapper
    func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/semgrep/commands/ci.py", line 306, in ci
    with fix_head_if_github_action(metadata):
  File "/usr/local/lib/python3.10/contextlib.py", line [13](https://github.com/xxx/xxx-webapp/runs/6915050329?check_suite_focus=true#step:4:14)5, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.10/site-packages/semgrep/commands/ci.py", line 83, in fix_head_if_github_action
    assert metadata.head_branch_hash is not None  # Not none when github action PR
  File "/usr/local/lib/python3.10/site-packages/boltons/cacheutils.py", line 641, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/local/lib/python3.10/site-packages/semgrep/meta.py", line 250, in head_branch_hash
    commit = self._get_latest_commit_hash_in_branch(head_branch_name)
  File "/usr/local/lib/python3.10/site-packages/semgrep/meta.py", line 238, in _get_latest_commit_hash_in_branch
    self._shallow_fetch_branch(branch_name)
  File "/usr/local/lib/python3.10/site-packages/semgrep/meta.py", line 2[15](https://github.com/xxx/xxx-webapp/runs/6915050329?check_suite_focus=true#step:4:16), in _shallow_fetch_branch
    subprocess.run(
  File "/usr/local/lib/python3.10/subprocess.py", line 5[24](https://github.com/xxx/xxx-webapp/runs/6915050329?check_suite_focus=true#step:4:25), in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'fetch', 'origin', '--depth=1', '--force', '--update-head-ok', 'fix-semgrep:fix-semgrep']' returned non-zero exit status 1[28](https://github.com/xxx/xxx-webapp/runs/6915050329?check_suite_focus=true#step:4:29).
```
I checked out the previously created https://github.com/returntocorp/semgrep-action/issues/569 and it was recommended to provide a workspace env https://github.com/returntocorp/semgrep-action/issues/569#issuecomment-1120574232
I tried this config
```yaml
  semgrep:
    name: Semgrep
    runs-on: ubuntu-20.04
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev'
    env:
      GITHUB_WORKSPACE: /github/workspace
    steps:
      - uses: actions/checkout@v1
      - name: Semgrep
        id: semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/r2c
```
But get the same error.
It seems to be related to the latest release https://github.com/returntocorp/semgrep-action/releases/tag/v1 which happened 11h ago, because before we were not facing this issue.

**Comment by lwsanty** [comment]
closing due to this issue https://github.com/returntocorp/semgrep/issues/5556 comment https://github.com/returntocorp/semgrep/issues/5556#issuecomment-1157471887 helped me
